(() => {
  const menuButton=document.querySelector('[data-menu-button]');
  const menu=document.querySelector('[data-mobile-menu]');
  const menuIcon=document.querySelector('[data-menu-icon]');
  if(menuButton&&menu){menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));menu.classList.toggle('hidden',open);if(menuIcon){menuIcon.classList.toggle('ph-list',open);menuIcon.classList.toggle('ph-x',!open);}})}
  const regBtn=document.querySelector('[data-registration-button]'); const regMenu=document.querySelector('[data-registration-menu]');
  if(regBtn&&regMenu){regBtn.addEventListener('click',()=>{const open=regBtn.getAttribute('aria-expanded')==='true';regBtn.setAttribute('aria-expanded',String(!open));regMenu.classList.toggle('hidden',open)});document.addEventListener('click',e=>{if(!regBtn.contains(e.target)&&!regMenu.contains(e.target)){regBtn.setAttribute('aria-expanded','false');regMenu.classList.add('hidden')}})}
  document.querySelectorAll('[data-tabs]').forEach(group=>{const tabs=[...group.querySelectorAll('[role="tab"]')]; tabs.forEach((tab,idx)=>{tab.tabIndex=tab.getAttribute('aria-selected')==='true'?0:-1;tab.addEventListener('click',()=>activate(tab));tab.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let next=idx;if(e.key==='ArrowRight')next=(idx+1)%tabs.length;if(e.key==='ArrowLeft')next=(idx-1+tabs.length)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;tabs[next].focus();activate(tabs[next]);});});function activate(tab){tabs.forEach(t=>{const selected=t===tab;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;const panel=document.getElementById(t.getAttribute('aria-controls'));if(panel)panel.hidden=!selected;t.classList.toggle('bg-[#e5187e]',selected);t.classList.toggle('bg-[#082f72]',!selected);});}});
  document.querySelectorAll('[data-accordion-item]').forEach(item=>{const btn=item.querySelector('button');const panel=item.querySelector('div[hidden]');if(!btn||!panel)return;btn.addEventListener('click',()=>{const open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));panel.hidden=open;const icon=btn.querySelector('i');if(icon){icon.classList.toggle('ph-plus',open);icon.classList.toggle('ph-minus',!open);}})});
  document.querySelectorAll('[data-filter-list]').forEach(list=>{const scope=list.parentElement;const buttons=scope.querySelectorAll('[data-filter-button]');buttons.forEach(btn=>btn.addEventListener('click',()=>{const f=btn.dataset.filterButton;buttons.forEach(b=>{b.classList.toggle('bg-[#e5187e]',b===btn);b.classList.toggle('text-white',b===btn);});list.querySelectorAll('[data-filter-item]').forEach(item=>item.hidden=!(f==='all'||item.dataset.filterItem===f));}));});
  const faqSearch=document.querySelector('[data-faq-search]');const faqList=document.querySelector('[data-faq-list]');const faqEmpty=document.querySelector('[data-faq-empty]');if(faqSearch&&faqList)faqSearch.addEventListener('input',()=>{const q=faqSearch.value.trim().toLowerCase();let shown=0;faqList.querySelectorAll('[data-accordion-item]').forEach(item=>{const match=item.textContent.toLowerCase().includes(q);item.hidden=!match;if(match)shown++;});if(faqEmpty)faqEmpty.classList.toggle('hidden',shown!==0);});
  const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced&&'IntersectionObserver'in window){document.documentElement.classList.add('reveal-ready');const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('[data-reveal]').forEach(el=>io.observe(el));}
})();